Repository wulkanowy/wulkanowy-web, pull requests merged in 2021-06, with the labels that each got.

#67 Messed up installation order in README.md
  README.md
Labels: documentation

#72 Fix Fakelog.cf mark 1
  app/API/dashboard.py
  app/API/messages.py
  app/login.py
  app/views.py
  frontend/src/api/login.ts
  tests/test_views.py
Labels: bug

#74 Add diaries
  frontend/package-lock.json
  frontend/src/api/login.ts
  frontend/src/assets/data/diary.json
  frontend/src/components/Login/UserLogin.vue
  frontend/src/props/LoginForm.ts
  frontend/src/store/index.ts
  frontend/src/store/login.ts
  frontend/tsconfig.json
Labels: enhancement
